### ISSUE TITLE
A few quick questions

### ISSUE THREAD

**Issue by BARNZ** [jcesarmobile/ssl-skip#1]
Thanks for this plugin - works great for testing some https specific functions like GPS and getUserMedia.

Just had a few questions:

- How come this plugin is needed and the `EnableHttpsSelfSigned` class that comes with capacitor doesn't seem to do the job? Have I missed something here?
- Do you know of an easy way to avoid loading this plugin when it comes time to build for prod? Or is manual removal of the plugin the only option?

**Comment by jcesarmobile** [comment]
Capacitor doesn’t come with a EnableHttpsSelfSigned class, not sure what you are talking about.

capacitor 3 allows to list the plugins you want to use with the includePlugins array (see  https://capacitorjs.com/docs/config ) so you could use environment variables to use some plugins for development and other plugins for production, this way you could skip the ssl-skip in production. Other than that, I think manually u installing would be the other way to go.
