### ISSUE TITLE
Conditional enabling and disabling of functionality.

### ISSUE THREAD

**Issue by applex90** [jcesarmobile/ssl-skip#7]
First of all, thank you very much for the great plugin. I initially tried it with Android, and it works perfectly. Later, I will also test it with iOS.

In my use case, I need to be able to deactivate the plugin because occasionally, I establish a connection to the WAN, where SSL verification is required. Is there a way to achieve this?

Thank you very much.

Kind regards,
Alex

**Comment by jcesarmobile** [comment]
It’s not possible to deactivate the plugin at the moment.

By SSL verification you mean you have SSL pinning implemented with some plugin? If so, both plugins will probably collide because they both implement the same method.

**Comment by applex90** [comment]
By SSL verification I mean that an HTTPS connection with a self-signed certificate results in an error and is therefore not possible in Android and iOS.  I don't use SSL pinning.

**Comment by jcesarmobile** [comment]
The plugin ignores the errors produced by self signed certificates and allow to connect despite the error, so you want it to error when connected to the WAN? or to only ignore the errors for the WAN connections but not ignore the errors outside the WAN?

Anyway, android code would almost certainly produce app rejection on Google play, so you should remove the plugin when submitting the app, so if what you want is to be able to connect to your WAN in the production app despite the self signed certificates, you should ship the certificate with the app and make the app install the certificate on the device so it trust it, I’ve done that in the past and worked, not sure if that would still work in modern android version. We ended using good certificates even on the local network.

**Comment by applex90** [comment]
Thanks for your detailed answer.  I would like to make it more specific.  In the LAN we use self-signed certificates, so it is necessary to deactivate the errors with your plugin.  But in the WAN, i.e. when connecting to a cloud server, a correct certificate is used, so in my opinion the functionality of the plugin must be deactivated again.  It would also be ok for me if we didn't publish the app via a store, but just provided an APK file.  Excuse my inexperience, I'm still fairly new to the field.

**Comment by Zefau** [comment]
@applex90 there you go https://github.com/jcesarmobile/ssl-skip/pull/12

**Comment by sidibukhari** [comment]
I don't think it possible to do because the way Google check is they check on the code that bypass the ssl check. By having the code but is not turn on, they will still flag it as bypassing the ssl check. That's how I understand their checking because using cordova previously, when we put a condition, it still flag as we bypass the ssl check.

**Comment by jcesarmobile** [comment]
Closing as won't do.
I see no point for disabling the plugin, the plugin allows to ignore SSL errors and allow connections. Valid connections will still work with the plugin enabled.

The plugin needs to be uninstalled for submissions to the stores as it will cause rejections, so disabling it wouldn't be enough.
